# Generated by Django 3.0.4 on 2021-11-04 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Aplicaciones',
            },
        ),
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania', models.CharField(max_length=200, null=True)),
                ('periodo1_inflado', models.IntegerField(default=30)),
                ('periodo2_inflado', models.IntegerField(default=60)),
                ('periodo1_inspeccion', models.IntegerField(default=30)),
                ('periodo2_inspeccion', models.IntegerField(default=60)),
                ('punto_retiro_eje_direccion', models.IntegerField(default=3)),
                ('punto_retiro_eje_traccion', models.IntegerField(default=3)),
                ('punto_retiro_eje_arrastre', models.IntegerField(default=3)),
                ('punto_retiro_eje_loco', models.IntegerField(default=3)),
                ('punto_retiro_eje_retractil', models.IntegerField(default=3)),
                ('mm_de_diferencia_entre_duales', models.IntegerField(default=3)),
                ('mm_parametro_sospechoso', models.IntegerField(default=5)),
                ('unidades_presion', models.CharField(choices=[('psi', 'psi'), ('bar', 'bar'), ('mPa', 'mPa')], default='psi', max_length=200)),
                ('unidades_profundidad', models.CharField(choices=[('mm', 'mm'), ("32''", "32''")], default='mm', max_length=200)),
                ('objetivo', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Compania')),
            ],
            options={
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_economico', models.CharField(max_length=100)),
                ('modelo', models.CharField(default='Demo', max_length=200, null=True)),
                ('marca', models.CharField(default='Demo', max_length=200, null=True)),
                ('numero_de_llantas', models.PositiveIntegerField(default=8)),
                ('clase', models.CharField(blank=True, choices=[('AUTOTANQUE ALIMENTICIO', 'Autotanque Alimenticio'), ('AUTOTANQUE COMBUSTIBLE', 'Autotanque Combustible'), ('AUTOTANQUE QUIMICOS', 'Autotanque Químicos'), ('CAJA REFRIGERADO 48', 'Caja Refrigerado 48'), ('CAJA SECA', 'Caja Seca'), ('CAJA SECA 40', 'Caja Seca 40'), ('CAJA SECA 48', 'Caja Seca 48'), ('CAJA SECA 53', 'Caja Seca 53'), ('CAJA SECA 53 (3 EJES)', 'Caja Seca 53 (3 Ejes)'), ('CAMIÓN - CAMAROTE', 'Camión - Camarote'), ('CAMIONETA', 'Camioneta'), ('CORTINA', 'Cortina'), ('CORTINA 38', 'Cortina 38'), ('DOLLY', 'Dolly'), ('PICK-UP', 'Pick-Up'), ('PLATAFORMA 35', 'Plataforma 35'), ('PLATAFORMA 40', 'Plataforma 40'), ('PLATAFORMA 53', 'Plataforma 53'), ('PLATAFORMA 53 (3 EJES)', 'Plataforma 53 (3 Ejes)'), ('PORTACONTENEDOR', 'Portacontenedor'), ('RABON', 'Rabon'), ('REMOLQUE', 'Remolque'), ('REMOLQUE - CAJA SECA', 'Remolque - Caja Seca'), ('THERMOKING THORTON CAJA 25', 'Thermoking Thorton Caja 25'), ('TOLVA', 'Tolva'), ('TORTHON', 'Torthon'), ('TORTHON REFRIGERADO', 'Torthon Refrigerado'), ('TORTHON SECO', 'Torthon Seco'), ('TRACTOR', 'Tractor'), ('TRACTOCAMION', 'Tractocamion'), ('UTILITARIO TALLER', 'Utilitario Taller'), ('UTILITARIO ADMINISTRATIVO', 'Utilitario Administrativo'), ('YARD TRUCK', 'Yard Truck')], max_length=200, null=True)),
                ('configuracion', models.CharField(blank=True, choices=[('S2.D2', 'S2.D2'), ('S2.D2.D2', 'S2.D2.D2'), ('S2.D2.D2.T4.T4', 'S2.D2.D2.T4.T4'), ('S2.D4', 'S2.D4'), ('S2.D4.C4.SP1', 'S2.D4.C4.SP1'), ('S2.D4.D4', 'S2.D4.D4'), ('S2.D4.D4.D4', 'S2.D4.D4.D4'), ('S2.D4.D4.L2', 'S2.D4.D4.L2'), ('S2.D4.D4.SP1', 'S2.D4.D4.SP1'), ('S2.D4.D4.T4.T4', 'S2.D4.D4.T4.T4'), ('S2.D4.L4', 'S2.D4.L4'), ('S2.L2.D4', 'S2.L2.D4'), ('S2.L2.D4.D4', 'S2.L2.D4.D4'), ('S2.L2.D4.D4.D2', 'S2.L2.D4.D4.D2'), ('S2.L2.D4.D4.L2', 'S2.L2.D4.D4.L2'), ('S2.L2.D4.D4.L4', 'S2.L2.D4.D4.L4'), ('S2.L2.L2.D4.D4', 'S2.L2.L2.D4.D4'), ('S2.L2.L2.D4.D4.L2', 'S2.L2.L2.D4.D4.L2'), ('S2.L2.L2.L2.D4.D4', 'S2.L2.L2.L2.D4.D4'), ('S2.L2.L2.L2.L2.D4.D4', 'S2.L2.L2.L2.L2.D4.D4'), ('S2.L4.D4', 'S2.L4.D4'), ('S2.L4.D4.D4', 'S2.L4.D4.D4')], max_length=200, null=True)),
                ('fecha_de_inflado', models.DateField(blank=True, null=True)),
                ('fecha_hora_de_inspeccion', models.DateTimeField(blank=True, null=True)),
                ('tiempo_de_inflado', models.FloatField(blank=True, null=True)),
                ('presion_de_entrada', models.IntegerField(blank=True, null=True)),
                ('presion_de_salida', models.IntegerField(blank=True, null=True)),
                ('presion_establecida', models.IntegerField(blank=True, default=100, null=True)),
                ('fecha_de_creacion', models.DateField(auto_now_add=True)),
                ('aplicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.Aplicacion')),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Compania')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.Ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(choices=[('Español', 'Español'), ('Inglés', 'Inglés')], default='Español', max_length=200)),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True)),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Compania')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Llanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_economico', models.CharField(max_length=200, null=True)),
                ('producto', models.CharField(default=None, max_length=200, null=True)),
                ('marca', models.CharField(max_length=200, null=True)),
                ('tipo_de_eje', models.CharField(max_length=4, null=True)),
                ('eje', models.IntegerField(blank=True, null=True)),
                ('posicion', models.CharField(max_length=4, null=True)),
                ('presion_encontrada', models.IntegerField(blank=True, default=100, null=True)),
                ('presion_actual', models.IntegerField(blank=True, default=100, null=True)),
                ('presion_establecida', models.IntegerField(blank=True, default=100, null=True)),
                ('fecha_de_inflado', models.DateField(blank=True, null=True)),
                ('fecha_hora_de_inspeccion', models.DateTimeField(blank=True, null=True)),
                ('tiempo_de_inspeccion', models.FloatField(blank=True, default=2, null=True)),
                ('primera_min_profundidad', models.IntegerField(blank=True, null=True)),
                ('primera_max_profundidad', models.IntegerField(blank=True, default=2, null=True)),
                ('min_profundidad', models.IntegerField(blank=True, null=True)),
                ('max_profundidad', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Perfil')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometraje', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('tiempo_de_inspeccion', models.FloatField(blank=True, default=2, null=True)),
                ('min_profundidad', models.IntegerField(blank=True, null=True)),
                ('max_profundidad', models.IntegerField(blank=True, null=True)),
                ('llanta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Llanta')),
            ],
            options={
                'verbose_name_plural': 'Inspecciones',
            },
        ),
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Compania')),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_inflado', models.DateField(blank=True, null=True)),
                ('tiempo_de_inflado', models.FloatField(blank=True, default=2, null=True)),
                ('presion_de_entrada', models.IntegerField(blank=True, default=100, null=True)),
                ('presion_de_salida', models.IntegerField(blank=True, default=100, null=True)),
                ('presion_establecida', models.IntegerField(blank=True, default=100, null=True)),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Compania')),
                ('numero_economico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='compania',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Compania'),
        ),
    ]
