# Generated by Django 4.0.3 on 2022-05-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_perfil_taller_alter_perfil_compania'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='aplicaciones',
            field=models.ManyToManyField(blank=True, null=True, related_name='aplicaciones', to='dashboards.aplicacion'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='companias',
            field=models.ManyToManyField(blank=True, null=True, related_name='companias', to='dashboards.compania'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='talleres',
            field=models.ManyToManyField(blank=True, null=True, related_name='talleres', to='dashboards.taller'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ubicaciones',
            field=models.ManyToManyField(blank=True, null=True, related_name='ubicaciones', to='dashboards.ubicacion'),
        ),
    ]
