# Generated by Django 3.0.4 on 2021-11-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_remove_llanta_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='llanta',
            name='producto',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
