# Generated by Django 4.0.3 on 2022-05-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_perfil_aplicaciones_perfil_companias_perfil_talleres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='aplicacion',
        ),
        migrations.AddField(
            model_name='perfil',
            name='aplicacion',
            field=models.ManyToManyField(blank=True, null=True, to='dashboards.aplicacion'),
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='taller',
        ),
        migrations.AddField(
            model_name='perfil',
            name='taller',
            field=models.ManyToManyField(blank=True, null=True, to='dashboards.taller'),
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='perfil',
            name='ubicacion',
            field=models.ManyToManyField(blank=True, null=True, to='dashboards.ubicacion'),
        ),
    ]
