# Generated by Django 4.0.2 on 2022-05-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_remove_perfil_aplicacion_perfil_aplicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccion',
            name='observaciones',
            field=models.ManyToManyField(blank=True, limit_choices_to={'nivel': 'Llanta'}, null=True, to='dashboards.Observacion'),
        ),
        migrations.AlterField(
            model_name='inspeccionvehiculo',
            name='observaciones',
            field=models.ManyToManyField(blank=True, limit_choices_to={'nivel': 'Vehiculo'}, null=True, to='dashboards.Observacion'),
        ),
        migrations.AlterField(
            model_name='llanta',
            name='observaciones',
            field=models.ManyToManyField(blank=True, limit_choices_to={'nivel': 'Llanta'}, null=True, to='dashboards.Observacion'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='aplicacion',
            field=models.ManyToManyField(blank=True, null=True, to='dashboards.Aplicacion'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='aplicaciones',
            field=models.ManyToManyField(blank=True, null=True, related_name='aplicaciones', to='dashboards.Aplicacion'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='companias',
            field=models.ManyToManyField(blank=True, null=True, related_name='companias', to='dashboards.Compania'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='taller',
            field=models.ManyToManyField(blank=True, null=True, to='dashboards.Taller'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='talleres',
            field=models.ManyToManyField(blank=True, null=True, related_name='talleres', to='dashboards.Taller'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ubicacion',
            field=models.ManyToManyField(blank=True, null=True, to='dashboards.Ubicacion'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ubicaciones',
            field=models.ManyToManyField(blank=True, null=True, related_name='ubicaciones', to='dashboards.Ubicacion'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='observaciones',
            field=models.ManyToManyField(blank=True, limit_choices_to={'nivel': 'Vehiculo'}, null=True, to='dashboards.Observacion'),
        ),
    ]
