# Generated by Django 4.0.3 on 2022-05-25 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_alter_inspeccion_observaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlantasSeleccionadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llantas', models.ManyToManyField(blank=True, null=True, to='dashboards.llanta')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.perfil')),
            ],
            options={
                'verbose_name_plural': 'LlantasSeleccionadas',
            },
        ),
    ]
