# Generated by Django 4.0.3 on 2022-05-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_llantasseleccionadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='llantasseleccionadas',
            name='inventario',
            field=models.CharField(blank=True, choices=[('Nueva', 'Nueva'), ('Antes de Renovar', 'Antes de Renovar'), ('Antes de Desechar', 'Antes de Desechar'), ('Renovada', 'Renovada'), ('Con renovador', 'Con renovador'), ('Desecho final', 'Desecho final'), ('Servicio', 'Servicio'), ('Rodante', 'Rodante'), ('Archivado', 'Archivado')], max_length=200, null=True),
        ),
    ]
