# Generated by Django 4.0.2 on 2022-05-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_alter_observacion_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llantasseleccionadas',
            name='llantas',
            field=models.ManyToManyField(blank=True, null=True, to='dashboards.Llanta'),
        ),
    ]
