# Generated by Django 3.0.4 on 2021-11-16 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_auto_20211114_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llanta',
            name='fecha_hora_de_inspeccion',
        ),
        migrations.RemoveField(
            model_name='llanta',
            name='max_profundidad',
        ),
        migrations.RemoveField(
            model_name='llanta',
            name='min_profundidad',
        ),
        migrations.RemoveField(
            model_name='llanta',
            name='primera_max_profundidad',
        ),
        migrations.RemoveField(
            model_name='llanta',
            name='primera_min_profundidad',
        ),
        migrations.RemoveField(
            model_name='llanta',
            name='tiempo_de_inspeccion',
        ),
        migrations.AddField(
            model_name='llanta',
            name='ultima_inspeccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='dashboards.Inspeccion'),
        ),
    ]
