# Generated by Django 4.0.2 on 2022-05-27 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_alter_vehiculo_configuracion'),
        ('dashboards', '0009_alter_llantasseleccionadas_llantas'),
    ]

    operations = [
    ]
