# Generated by Django 3.0.4 on 2021-11-17 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0009_auto_20211116_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='llanta',
            old_name='presion_actual',
            new_name='presion_de_entrada',
        ),
        migrations.RenameField(
            model_name='llanta',
            old_name='presion_encontrada',
            new_name='presion_de_salida',
        ),
    ]
