# Generated by Django 4.0.3 on 2022-05-28 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_merge_20220526_2314'),
        ('dashboards', '0010_merge_20220526_2329'),
    ]

    operations = [
    ]
