# Generated by Django 3.0.4 on 2021-11-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_auto_20211117_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='llanta',
            name='primera_max_profundidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llanta',
            name='primera_min_profundidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
