# Generated by Django 4.0.3 on 2022-05-28 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0011_merge_20220527_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rechazo',
            name='llanta',
        ),
        migrations.AddField(
            model_name='llanta',
            name='rechazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboards.rechazo'),
        ),
        migrations.AddField(
            model_name='rechazo',
            name='compania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.compania'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='status',
            field=models.CharField(choices=[('PreOrden', 'PreOrden'), ('Orden', 'Orden'), ('AntesRenovar', 'AntesRenovar'), ('CambioTaller', 'CambioTaller'), ('CambioStock', 'CambioStock')], max_length=200),
        ),
    ]
