# Generated by Django 4.0.3 on 2022-05-28 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0012_remove_rechazo_llanta_llanta_rechazo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechazo',
            name='compania',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.compania'),
        ),
    ]
