# Generated by Django 3.0.4 on 2021-11-19 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0012_auto_20211117_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccion',
            name='llanta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_llanta', to='dashboards.Llanta'),
        ),
    ]
