# Generated by Django 3.0.4 on 2021-11-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0013_auto_20211118_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccion',
            name='max_profundidad',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='min_profundidad',
            field=models.IntegerField(default=3),
        ),
    ]
