# Generated by Django 4.0.3 on 2022-05-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0013_alter_rechazo_compania'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='imagen',
            field=models.ImageField(null=True, upload_to='desecho'),
        ),
    ]
