# Generated by Django 3.0.4 on 2021-11-19 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0014_auto_20211119_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llanta',
            name='primera_max_profundidad',
        ),
        migrations.RemoveField(
            model_name='llanta',
            name='primera_min_profundidad',
        ),
    ]
