# Generated by Django 4.0.3 on 2022-05-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0014_orden_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='status',
            field=models.CharField(choices=[('PreOrden', 'PreOrden'), ('Orden', 'Orden'), ('AntesRenovar', 'AntesRenovar'), ('ConRenovador', 'ConRenovador'), ('CambioTaller', 'CambioTaller'), ('CambioStock', 'CambioStock')], max_length=200),
        ),
    ]
