# Generated by Django 4.0.3 on 2022-05-30 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0015_alter_orden_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDesecho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=200)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('min_profundidad', models.IntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='desecho')),
                ('desecho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.desecho')),
                ('llanta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.llanta')),
            ],
            options={
                'verbose_name_plural': 'OrdenDesecho',
            },
        ),
    ]
