# Generated by Django 3.0.4 on 2021-11-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0016_auto_20211119_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compania',
            name='mm_parametro_sospechoso',
            field=models.FloatField(default=5),
        ),
    ]
