# Generated by Django 4.0.3 on 2022-05-30 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0016_ordendesecho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordendesecho',
            options={'verbose_name_plural': 'OrdenesDesechos'},
        ),
    ]
