# Generated by Django 4.0.3 on 2022-05-30 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0017_alter_ordendesecho_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendesecho',
            name='compania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.compania'),
        ),
    ]
