# Generated by Django 3.0.4 on 2021-11-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0017_auto_20211123_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='llanta',
            name='vida',
            field=models.CharField(blank=True, choices=[('Nueva', 'Nueva'), ('1R', '1R'), ('2R', '2R'), ('3R', '3R'), ('4R', '4R'), ('5R', '5R')], max_length=200, null=True),
        ),
    ]
