# Generated by Django 3.0.4 on 2021-11-25 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0018_llanta_vida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llanta',
            name='vida',
        ),
    ]
