# Generated by Django 4.0.3 on 2022-05-30 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0018_ordendesecho_compania'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendesecho',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.perfil'),
        ),
    ]
