# Generated by Django 4.0.3 on 2022-05-31 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0019_ordendesecho_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='llanta',
            name='renovador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.renovador'),
        ),
    ]
