# Generated by Django 3.0.4 on 2021-11-29 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0020_llanta_vida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspeccion',
            name='kilometraje',
        ),
    ]
