# Generated by Django 4.0.3 on 2022-06-04 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_merge_20220526_2344'),
        ('dashboards', '0020_llanta_renovador'),
    ]

    operations = [
    ]
