# Generated by Django 4.0.3 on 2022-06-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0020_llanta_renovador'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='dias_alinear',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='dias_inspeccion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_ultima_alineacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_ultima_inspeccion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
