# Generated by Django 4.0.3 on 2022-06-05 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0021_merge_0010_merge_20220526_2344_0020_llanta_renovador'),
        ('dashboards', '0021_vehiculo_dias_alinear_vehiculo_dias_inspeccion_and_more'),
    ]

    operations = [
    ]
