# Generated by Django 3.0.4 on 2021-11-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0021_remove_inspeccion_kilometraje'),
    ]

    operations = [
        migrations.AddField(
            model_name='llanta',
            name='nombre_de_eje',
            field=models.CharField(blank=True, choices=[('Dirección', 'Dirección'), ('Tracción', 'Tracción'), ('Arrastre', 'Arrastre'), ('Loco', 'Loco'), ('Retractil', 'Retractil')], max_length=200, null=True),
        ),
    ]
