# Generated by Django 3.0.4 on 2021-11-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0022_llanta_nombre_de_eje'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='rendimiento_de_cuarta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='rendimiento_de_nueva',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='rendimiento_de_primera',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='rendimiento_de_segunda',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='rendimiento_de_tercera',
            field=models.IntegerField(default=5),
        ),
    ]
