# Generated by Django 3.2.9 on 2021-12-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0023_auto_20211129_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='precio_nueva',
            field=models.IntegerField(default=4000),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='precio_nueva_direccion',
            field=models.IntegerField(default=5500),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='precio_renovada',
            field=models.IntegerField(default=2000),
        ),
    ]
