# Generated by Django 4.0.3 on 2022-06-06 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0022_merge_20220605_1613'),
        ('dashboards', '0023_vehiculo_observaciones_llanta'),
    ]

    operations = [
    ]
