# Generated by Django 4.0.2 on 2022-06-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0024_merge_20220605_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='observaciones_llanta',
            field=models.ManyToManyField(blank=True, limit_choices_to={'nivel': 'Llanta'}, null=True, related_name='observaciones_llanta', to='dashboards.Observacion'),
        ),
    ]
