# Generated by Django 3.0.4 on 2021-12-03 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0024_auto_20211130_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspeccion',
            old_name='tiempo_de_inspeccion',
            new_name='tiempo_de_inspecciones',
        ),
    ]
