# Generated by Django 4.0.2 on 2022-06-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0025_alter_vehiculo_observaciones_llanta'),
        ('dashboards', '0025_llanta_fecha_de_balanceado'),
    ]

    operations = [
    ]
