# Generated by Django 3.0.4 on 2021-12-03 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0025_auto_20211202_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspeccion',
            old_name='tiempo_de_inspecciones',
            new_name='tiempo_de_inspeccion',
        ),
    ]
