# Generated by Django 3.0.4 on 2022-01-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0026_auto_20211202_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='km',
            field=models.IntegerField(default=1000),
        ),
    ]
