# Generated by Django 4.0.3 on 2022-06-23 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0026_merge_20220617_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=200)),
                ('fecha_real', models.DateField(blank=True, null=True)),
                ('horario_real', models.TimeField(blank=True, null=True)),
                ('configuracion', models.CharField(max_length=1000)),
                ('aplicacion', models.ManyToManyField(blank=True, null=True, to='dashboards.aplicacion')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.ubicacion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboards.perfil')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioLlanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inflado', models.BooleanField()),
                ('balanceado', models.BooleanField()),
                ('reparado', models.BooleanField()),
                ('valvula_reparada', models.BooleanField()),
                ('costado_reparado', models.BooleanField()),
                ('rotar', models.BooleanField()),
                ('rotar_otro', models.BooleanField()),
                ('rotar_mismo', models.BooleanField()),
                ('llanta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.llanta')),
                ('llanta_cambio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NuevaLlanta', to='dashboards.llanta')),
                ('serviciovehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboards.serviciovehiculo')),
            ],
        ),
    ]
