# Generated by Django 4.0.3 on 2022-06-23 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0028_alter_serviciovehiculo_configuracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciovehiculo',
            name='aplicacion',
        ),
        migrations.AddField(
            model_name='serviciovehiculo',
            name='aplicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.aplicacion'),
        ),
        migrations.AlterField(
            model_name='serviciovehiculo',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
