# Generated by Django 4.0.3 on 2022-06-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0029_remove_serviciovehiculo_aplicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciovehiculo',
            name='alineacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviciollanta',
            name='balanceado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviciollanta',
            name='costado_reparado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviciollanta',
            name='inflado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviciollanta',
            name='reparado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviciollanta',
            name='rotar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviciollanta',
            name='rotar_mismo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviciollanta',
            name='rotar_otro',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviciollanta',
            name='valvula_reparada',
            field=models.BooleanField(default=False),
        ),
    ]
