# Generated by Django 3.0.4 on 2022-01-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0029_auto_20220118_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='aplicacion',
            field=models.CharField(choices=[('Dirección', 'Dirección'), ('Tracción', 'Tracción'), ('Arrastre', 'Arrastre'), ('Mixta', 'Mixta'), ('Regional', 'Regional')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='profundidad_inicial',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='vida',
            field=models.CharField(choices=[('Nueva', 'Nueva'), ('Renovada', 'Renovada'), ('Vitacasco', 'Vitacasco')], max_length=100, null=True),
        ),
    ]
