# Generated by Django 3.2.9 on 2022-01-24 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0030_auto_20220121_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='llanta',
            name='nombre_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.producto'),
        ),
    ]
