# Generated by Django 4.0.3 on 2022-06-24 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0030_serviciovehiculo_alineacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciollanta',
            name='desmontaje',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviciollanta',
            name='inventario_de_desmontaje',
            field=models.CharField(blank=True, choices=[('Nueva', 'Nueva'), ('Antes de Renovar', 'Antes de Renovar'), ('Antes de Desechar', 'Antes de Desechar'), ('Renovada', 'Renovada'), ('Con renovador', 'Con renovador'), ('Desecho final', 'Desecho final'), ('Servicio', 'Servicio'), ('Rodante', 'Rodante'), ('Archivado', 'Archivado')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='serviciollanta',
            name='razon_de_desmontaje',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='serviciollanta',
            name='taller_de_desmontaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboards.taller'),
        ),
    ]
