# Generated by Django 4.0.3 on 2022-06-24 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0031_serviciollanta_desmontaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciollanta',
            name='llanta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboards.llanta'),
        ),
        migrations.AlterField(
            model_name='serviciollanta',
            name='llanta_cambio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NuevaLlanta', to='dashboards.llanta'),
        ),
    ]
