# Generated by Django 4.0.3 on 2022-06-27 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0032_alter_serviciollanta_llanta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora_Desecho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('porcentaje_util_desechado', models.FloatField()),
                ('mm_desechados', models.FloatField()),
                ('valor_casco', models.FloatField()),
                ('valor_banda_rodamiento', models.FloatField()),
                ('profundidad_de_desecho', models.FloatField()),
                ('perdida_total', models.FloatField()),
                ('foto', models.URLField()),
                ('desecho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.desecho')),
                ('llanta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.llanta')),
            ],
        ),
    ]
