# Generated by Django 3.2.9 on 2022-01-24 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0032_auto_20220124_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='kilometraje_proyectado',
            new_name='km_proyectado',
        ),
        migrations.RemoveField(
            model_name='llanta',
            name='producto',
        ),
    ]
