# Generated by Django 4.0.3 on 2022-06-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0033_bitacora_desecho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llanta',
            name='desecho',
        ),
    ]
