# Generated by Django 4.0.3 on 2022-06-29 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0034_remove_llanta_desecho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitacora_desecho',
            options={'verbose_name_plural': 'Bitacoras Desecho'},
        ),
        migrations.CreateModel(
            name='Rendimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mm_desgastados', models.FloatField()),
                ('porcentaje_de_desgaste', models.FloatField()),
                ('km_x_mm', models.FloatField()),
                ('km_proyectado', models.FloatField()),
                ('analizada', models.FloatField()),
                ('cpk_proyectado', models.FloatField()),
                ('cpk_real', models.FloatField()),
                ('llanta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.llanta')),
                ('mes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.desecho')),
            ],
        ),
    ]
