# Generated by Django 3.0.4 on 2022-01-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0034_rename_nombre_producto_llanta_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='aplicacion',
            field=models.CharField(choices=[('Dirección', 'Dirección'), ('Tracción', 'Tracción'), ('Arrastre', 'Arrastre'), ('Mixta', 'Mixta'), ('Regional', 'Regional'), ('Urbano', 'Urbano')], max_length=100, null=True),
        ),
    ]
