# Generated by Django 3.0.4 on 2022-01-25 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0035_auto_20220124_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora_Pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_inflado', models.DateField(blank=True, null=True)),
                ('tiempo_de_inflado', models.FloatField(blank=True, null=True)),
                ('presion_de_entrada_1', models.IntegerField(blank=True, null=True)),
                ('presion_de_salida_1', models.IntegerField(blank=True, null=True)),
                ('presion_de_entrada_2', models.IntegerField(blank=True, null=True)),
                ('presion_de_salida_2', models.IntegerField(blank=True, null=True)),
                ('presion_de_entrada_3', models.IntegerField(blank=True, null=True)),
                ('presion_de_salida_3', models.IntegerField(blank=True, null=True)),
                ('presion_de_entrada_4', models.IntegerField(blank=True, null=True)),
                ('presion_de_salida_4', models.IntegerField(blank=True, null=True)),
                ('presion_de_entrada_5', models.IntegerField(blank=True, null=True)),
                ('presion_de_salida_5', models.IntegerField(blank=True, null=True)),
                ('presion_de_entrada_6', models.IntegerField(blank=True, null=True)),
                ('presion_de_salida_6', models.IntegerField(blank=True, null=True)),
                ('presion_de_entrada_7', models.IntegerField(blank=True, null=True)),
                ('presion_de_salida_7', models.IntegerField(blank=True, null=True)),
                ('presion_de_entrada_8', models.IntegerField(blank=True, null=True)),
                ('presion_de_salida_8', models.IntegerField(blank=True, null=True)),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Compania')),
                ('numero_economico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Vehiculo')),
            ],
        ),
    ]
