# Generated by Django 4.0.3 on 2022-07-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0035_alter_bitacora_desecho_options_rendimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviciovehiculo',
            old_name='fecha_real',
            new_name='fecha_inicio',
        ),
        migrations.RenameField(
            model_name='serviciovehiculo',
            old_name='horario_real',
            new_name='horario_inicio',
        ),
    ]
