# Generated by Django 4.0.3 on 2022-07-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0036_rename_fecha_real_serviciovehiculo_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciovehiculo',
            name='fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciovehiculo',
            name='horario_final',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
