# Generated by Django 3.0.4 on 2022-01-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0036_bitacora_pro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitacora_pro',
            options={'verbose_name_plural': 'Bitacoras Pro'},
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='presion_de_entrada_10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='presion_de_entrada_11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='presion_de_entrada_12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='presion_de_entrada_9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='presion_de_salida_10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='presion_de_salida_11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='presion_de_salida_12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='presion_de_salida_9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
