# Generated by Django 4.0.3 on 2022-07-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0037_serviciovehiculo_fecha_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciovehiculo',
            name='estado',
            field=models.CharField(blank=True, choices=[('abierto', 'abierto'), ('programado', 'programado'), ('cerrado', 'cerrado')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviciovehiculo',
            name='preguardado',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
