# Generated by Django 3.0.4 on 2022-01-25 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0037_auto_20220124_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='ultima_bitacora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras_pro', to='dashboards.Bitacora_Pro'),
        ),
    ]
