# Generated by Django 3.0.4 on 2022-02-14 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0038_vehiculo_ultima_bitacora'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='llanta',
            name='marca',
        ),
        migrations.AddField(
            model_name='llanta',
            name='km_montado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llanta',
            name='posicion',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='llanta',
            name='tipo_de_eje',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='llanta',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.Vehiculo'),
        ),
    ]
