# Generated by Django 4.0.3 on 2022-07-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0039_rename_preguardado_serviciovehiculo_preguardado_llantas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitacora',
            old_name='numero_economico',
            new_name='vehiculo',
        ),
        migrations.RenameField(
            model_name='bitacora_pro',
            old_name='numero_economico',
            new_name='vehiculo',
        ),
    ]
