# Generated by Django 4.0.2 on 2022-07-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0040_rename_numero_economico_bitacora_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llanta',
            name='nombre_de_eje',
            field=models.CharField(blank=True, choices=[('Dirección', 'Dirección'), ('Tracción', 'Tracción'), ('Arrastre', 'Arrastre'), ('Loco', 'Loco'), ('Retractil', 'Retractil'), ('Refacción', 'Refacción')], max_length=200, null=True),
        ),
    ]
