# Generated by Django 4.0.3 on 2022-07-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0042_alter_bitacora_fecha_de_inflado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccion',
            name='observaciones',
            field=models.ManyToManyField(limit_choices_to={'nivel': 'Llanta'}, to='dashboards.observacion'),
        ),
        migrations.AlterField(
            model_name='inspeccionvehiculo',
            name='observaciones',
            field=models.ManyToManyField(limit_choices_to={'nivel': 'Vehiculo'}, to='dashboards.observacion'),
        ),
        migrations.AlterField(
            model_name='llanta',
            name='observaciones',
            field=models.ManyToManyField(limit_choices_to={'nivel': 'Llanta'}, to='dashboards.observacion'),
        ),
        migrations.AlterField(
            model_name='llantasseleccionadas',
            name='llantas',
            field=models.ManyToManyField(to='dashboards.llanta'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='aplicacion',
            field=models.ManyToManyField(to='dashboards.aplicacion'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='aplicaciones',
            field=models.ManyToManyField(related_name='aplicaciones', to='dashboards.aplicacion'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='companias',
            field=models.ManyToManyField(related_name='companias', to='dashboards.compania'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='taller',
            field=models.ManyToManyField(to='dashboards.taller'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='talleres',
            field=models.ManyToManyField(related_name='talleres', to='dashboards.taller'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ubicacion',
            field=models.ManyToManyField(to='dashboards.ubicacion'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ubicaciones',
            field=models.ManyToManyField(related_name='ubicaciones', to='dashboards.ubicacion'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='observaciones',
            field=models.ManyToManyField(limit_choices_to={'nivel': 'Vehiculo'}, to='dashboards.observacion'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='observaciones_llanta',
            field=models.ManyToManyField(limit_choices_to={'nivel': 'Llanta'}, related_name='observaciones_llanta', to='dashboards.observacion'),
        ),
    ]
