# Generated by Django 4.0.3 on 2022-07-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0044_alter_perfil_aplicacion_alter_perfil_aplicaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='link_bi',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
