# Generated by Django 3.0.4 on 2022-03-09 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0044_tendenciacpk'),
    ]

    operations = [
        migrations.AddField(
            model_name='llanta',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.Ubicacion'),
        ),
    ]
