# Generated by Django 4.0.3 on 2022-07-22 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0045_perfil_link_bi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='link_bi',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='ultima_bitacora_pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_pro', to='dashboards.bitacora_pro'),
        ),
    ]
