# Generated by Django 4.0.3 on 2022-07-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0046_alter_perfil_link_bi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llanta',
            name='observaciones',
            field=models.ManyToManyField(blank=True, limit_choices_to={'nivel': 'Llanta'}, to='dashboards.observacion'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='observaciones',
            field=models.ManyToManyField(blank=True, limit_choices_to={'nivel': 'Vehiculo'}, to='dashboards.observacion'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='observaciones_llanta',
            field=models.ManyToManyField(blank=True, limit_choices_to={'nivel': 'Llanta'}, related_name='observaciones_llanta', to='dashboards.observacion'),
        ),
    ]
