# Generated by Django 3.0.4 on 2022-03-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0045_auto_20220315_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='aplicacion',
            field=models.CharField(blank=True, choices=[('Dirección', 'Dirección'), ('Tracción', 'Tracción'), ('Arrastre', 'Arrastre'), ('Mixta', 'Mixta'), ('Regional', 'Regional'), ('Urbano', 'Urbano')], max_length=100, null=True),
        ),
    ]
