# Generated by Django 3.0.4 on 2022-03-21 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0047_auto_20220315_1951'),
        ('dashboards', '0046_llanta_ubicacion'),
    ]

    operations = [
    ]
