# Generated by Django 4.0.3 on 2022-07-25 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0047_alter_llanta_observaciones_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='link_bi',
            new_name='link_pulpo',
        ),
    ]
