# Generated by Django 3.0.4 on 2022-03-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0048_merge_20220321_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='dibujo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='dimension',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='km_esperado',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='rango',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
