# Generated by Django 3.0.4 on 2022-03-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0049_auto_20220321_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='costo_por_km',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='km_proyectado',
        ),
        migrations.AlterField(
            model_name='producto',
            name='dibujo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='dimension',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='km_esperado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='rango',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
