# Generated by Django 4.0.3 on 2022-07-29 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0049_perfil_link_operativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciollanta',
            name='serviciovehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.serviciovehiculo'),
        ),
    ]
