# Generated by Django 4.0.3 on 2022-07-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0050_alter_serviciollanta_serviciovehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='llanta',
            name='parametro_desgaste_irregular',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
