# Generated by Django 3.0.4 on 2022-03-22 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0050_auto_20220321_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renovador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Compania')),
            ],
        ),
        migrations.CreateModel(
            name='Rechazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(max_length=200)),
                ('llanta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Llanta')),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(max_length=200)),
                ('color', models.CharField(choices=[('Verde', 'Verde'), ('Amarillo', 'Amarillo'), ('Rojo', 'Rojo'), ('Morado', 'Morado')], max_length=200)),
                ('llanta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Llanta')),
            ],
        ),
        migrations.CreateModel(
            name='Desecho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_de_llanta', models.CharField(max_length=200)),
                ('condicion', models.CharField(max_length=200)),
                ('razon', models.CharField(max_length=200)),
                ('llanta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Llanta')),
            ],
        ),
    ]
