# Generated by Django 3.0.4 on 2022-03-23 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0051_desecho_observacion_rechazo_renovador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renovador',
            options={'verbose_name_plural': 'Renovadores'},
        ),
        migrations.RemoveField(
            model_name='renovador',
            name='compania',
        ),
    ]
