# Generated by Django 4.0.3 on 2022-07-29 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0051_llanta_parametro_desgaste_irregular'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='llanta_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_1_pulpo', to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='llanta_10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_10_pulpo', to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='llanta_11',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_11_pulpo', to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='llanta_12',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_12_pulpo', to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='llanta_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_2_pulpo', to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='llanta_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_3_pulpo', to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='llanta_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_4_pulpo', to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='llanta_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_5_pulpo', to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='llanta_6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_6_pulpo', to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='llanta_7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_7_pulpo', to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='llanta_8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_8_pulpo', to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='llanta_9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_9_pulpo', to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='llanta_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_1_pulpopro', to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='llanta_10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_10_pulpopro', to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='llanta_11',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_11_pulpopro', to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='llanta_12',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_12_pulpopro', to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='llanta_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_2_pulpopro', to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='llanta_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_3_pulpopro', to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='llanta_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_4_pulpopro', to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='llanta_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_5_pulpopro', to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='llanta_6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_6_pulpopro', to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='llanta_7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_7_pulpopro', to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='llanta_8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_8_pulpopro', to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='llanta_9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llanta_9_pulpopro', to='dashboards.llanta'),
        ),
    ]
