# Generated by Django 4.0.3 on 2022-07-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0052_bitacora_llanta_1_bitacora_llanta_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='llantas',
            field=models.ManyToManyField(to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='presion_establecida_1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='presion_establecida_10',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='presion_establecida_11',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='presion_establecida_12',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='presion_establecida_2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='presion_establecida_3',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='presion_establecida_4',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='presion_establecida_5',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='presion_establecida_6',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='presion_establecida_7',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='presion_establecida_8',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='presion_establecida_9',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='llantas',
            field=models.ManyToManyField(to='dashboards.llanta'),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='presion_estacida_1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='presion_estacida_10',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='presion_estacida_11',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='presion_estacida_12',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='presion_estacida_2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='presion_estacida_3',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='presion_estacida_4',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='presion_estacida_5',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='presion_estacida_6',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='presion_estacida_7',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='presion_estacida_8',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='presion_estacida_9',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
    ]
