# Generated by Django 4.0.3 on 2022-07-30 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0053_bitacora_llantas_bitacora_presion_establecida_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitacora_pro',
            old_name='presion_estacida_1',
            new_name='presion_establecida_1',
        ),
        migrations.RenameField(
            model_name='bitacora_pro',
            old_name='presion_estacida_10',
            new_name='presion_establecida_10',
        ),
        migrations.RenameField(
            model_name='bitacora_pro',
            old_name='presion_estacida_11',
            new_name='presion_establecida_11',
        ),
        migrations.RenameField(
            model_name='bitacora_pro',
            old_name='presion_estacida_12',
            new_name='presion_establecida_12',
        ),
        migrations.RenameField(
            model_name='bitacora_pro',
            old_name='presion_estacida_2',
            new_name='presion_establecida_2',
        ),
        migrations.RenameField(
            model_name='bitacora_pro',
            old_name='presion_estacida_3',
            new_name='presion_establecida_3',
        ),
        migrations.RenameField(
            model_name='bitacora_pro',
            old_name='presion_estacida_4',
            new_name='presion_establecida_4',
        ),
        migrations.RenameField(
            model_name='bitacora_pro',
            old_name='presion_estacida_5',
            new_name='presion_establecida_5',
        ),
        migrations.RenameField(
            model_name='bitacora_pro',
            old_name='presion_estacida_6',
            new_name='presion_establecida_6',
        ),
        migrations.RenameField(
            model_name='bitacora_pro',
            old_name='presion_estacida_7',
            new_name='presion_establecida_7',
        ),
        migrations.RenameField(
            model_name='bitacora_pro',
            old_name='presion_estacida_8',
            new_name='presion_establecida_8',
        ),
        migrations.RenameField(
            model_name='bitacora_pro',
            old_name='presion_estacida_9',
            new_name='presion_establecida_9',
        ),
    ]
