# Generated by Django 3.0.4 on 2022-03-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0053_auto_20220323_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='compania',
            name='mm_de_desgaste_irregular',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='compania',
            name='unidades_distancia',
            field=models.CharField(choices=[('km', 'km'), ('mi', 'mi')], default='km', max_length=200),
        ),
    ]
