# Generated by Django 3.0.4 on 2022-03-23 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0054_auto_20220323_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Compania')),
            ],
            options={
                'verbose_name_plural': 'Talleres',
            },
        ),
    ]
