# Generated by Django 4.0.3 on 2022-07-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0054_rename_presion_estacida_1_bitacora_pro_presion_establecida_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='presion_establecida_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='presion_establecida_10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='presion_establecida_11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='presion_establecida_12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='presion_establecida_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='presion_establecida_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='presion_establecida_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='presion_establecida_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='presion_establecida_6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='presion_establecida_7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='presion_establecida_8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='presion_establecida_9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora_pro',
            name='presion_establecida_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora_pro',
            name='presion_establecida_10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora_pro',
            name='presion_establecida_11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora_pro',
            name='presion_establecida_12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora_pro',
            name='presion_establecida_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora_pro',
            name='presion_establecida_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora_pro',
            name='presion_establecida_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora_pro',
            name='presion_establecida_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora_pro',
            name='presion_establecida_6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora_pro',
            name='presion_establecida_7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora_pro',
            name='presion_establecida_8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora_pro',
            name='presion_establecida_9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
