# Generated by Django 3.0.4 on 2022-03-24 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0056_auto_20220323_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacion',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.Ubicacion'),
        ),
    ]
