# Generated by Django 4.0.3 on 2022-07-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0056_alter_ordendesecho_min_profundidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendimiento',
            name='mes',
            field=models.IntegerField(),
        ),
    ]
