# Generated by Django 4.0.3 on 2022-03-31 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0058_alter_vehiculo_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='clase',
            field=models.CharField(blank=True, choices=[('ARRASTRE', 'Arrastre'), ('TRUCK - BOX', 'Truck - Box'), ('VAN', 'Van'), ('TRUCK - DUMP', 'Truck - Dump'), ('TRAILER', 'Trailer'), ('VEHICLECLASSNAME', 'VehicleClassName'), ('AUTOBUS', 'Autobus'), ('AUTOMOVIL', 'Automovil'), ('AUTOTANQUE ALIMENTICIO', 'Autotanque Alimenticio'), ('AUTOTANQUE COMBUSTIBLE', 'Autotanque Combustible'), ('AUTOTANQUE QUIMICOS', 'Autotanque Químicos'), ('CAJA REFRIGERADO 48', 'Caja Refrigerado 48'), ('CAJA SECA', 'Caja Seca'), ('CAJA SECA 40', 'Caja Seca 40'), ('CAJA SECA 48', 'Caja Seca 48'), ('CAJA SECA 53', 'Caja Seca 53'), ('CAJA SECA 53 (3 EJES)', 'Caja Seca 53 (3 Ejes)'), ('CAMIÓN', 'Camión'), ('CAMIÓN - CAMAROTE', 'Camión - Camarote'), ('CAMIONETA', 'Camioneta'), ('CAMIONETA LIGERA', 'Camioneta ligera'), ('CORTINA', 'Cortina'), ('CORTINA 38', 'Cortina 38'), ('DOLLY', 'Dolly'), ('MOTOCICLETA', 'Motocicleta'), ('PICK-UP', 'Pick-Up'), ('PLATAFORMA 35', 'Plataforma 35'), ('PLATAFORMA 40', 'Plataforma 40'), ('PLATAFORMA 53', 'Plataforma 53'), ('PLATAFORMA 53 (3 EJES)', 'Plataforma 53 (3 Ejes)'), ('PORTACONTENEDOR', 'Portacontenedor'), ('RABON', 'Rabon'), ('REMOLQUE', 'Remolque'), ('REMOLQUE - CAJA SECA', 'Remolque - Caja Seca'), ('THERMOKING THORTON CAJA 25', 'Thermoking Thorton Caja 25'), ('TOLVA', 'Tolva'), ('TORTHON', 'Torthon'), ('TORTHON REFRIGERADO', 'Torthon Refrigerado'), ('TORTHON SECO', 'Torthon Seco'), ('TRACTOR', 'Tractor'), ('TRACTOCAMION', 'Tractocamion'), ('UTILITARIO TALLER', 'Utilitario Taller'), ('UTILITARIO ADMINISTRATIVO', 'Utilitario Administrativo'), ('YARD TRUCK', 'Yard Truck')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='ultima_bitacora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='dashboards.bitacora'),
        ),
    ]
