# Generated by Django 4.0.3 on 2022-08-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0058_inspeccionvehiculo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccionvehiculo',
            name='observaciones',
            field=models.ManyToManyField(blank=True, limit_choices_to={'nivel': 'Vehiculo'}, to='dashboards.observacion'),
        ),
    ]
