# Generated by Django 4.0.3 on 2022-08-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0059_alter_inspeccionvehiculo_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='llanta',
            name='patito',
            field=models.BooleanField(default=False),
        ),
    ]
