# Generated by Django 4.0.3 on 2022-04-01 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0058_auto_20220326_1951'),
        ('dashboards', '0059_alter_vehiculo_clase_alter_vehiculo_marca_and_more'),
    ]

    operations = [
    ]
