# Generated by Django 4.0.3 on 2022-08-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0060_llanta_patito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendimiento',
            name='analizada',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='cpk_proyectado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='cpk_real',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='km_proyectado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='km_x_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='mes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='mm_desgastados',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='porcentaje_de_desgaste',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
