# Generated by Django 4.0.3 on 2022-08-02 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0061_alter_rendimiento_analizada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendimiento',
            name='analizada',
        ),
    ]
