# Generated by Django 4.0.3 on 2022-04-05 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0062_alter_vehiculo_clase_delete_tendenciacpk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TendenciaCPK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('cantidad', models.CharField(max_length=200)),
                ('vida', models.CharField(max_length=200)),
                ('calificacion', models.CharField(max_length=200)),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.compania')),
            ],
        ),
    ]
