# Generated by Django 4.0.3 on 2022-08-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0062_remove_rendimiento_analizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendimiento',
            name='is_analizada',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
