# Generated by Django 4.0.3 on 2022-04-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0063_tendenciacpk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tendenciacpk',
            name='vida',
            field=models.CharField(choices=[('Nueva', 'Nueva'), ('1R', '1R'), ('2R', '2R'), ('3R', '3R'), ('4R', '4R'), ('5R', '5R')], max_length=200),
        ),
    ]
