# Generated by Django 4.0.3 on 2022-08-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0063_rendimiento_is_analizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_año', models.DateField(blank=True, null=True)),
                ('presupuesto', models.IntegerField()),
                ('gasto_real', models.IntegerField()),
                ('km_recorridos', models.IntegerField()),
                ('compania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.compania')),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboards.ubicacion')),
            ],
        ),
    ]
