# Generated by Django 4.0.3 on 2022-04-05 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0064_alter_tendenciacpk_vida'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TendenciaCPK',
        ),
    ]
