# Generated by Django 4.0.3 on 2022-08-02 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0064_presupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='compania',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.compania'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='mes_año',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboards.ubicacion'),
        ),
    ]
