# Generated by Django 4.0.3 on 2022-04-05 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0065_delete_tendenciacpk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TendenciaCPK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('cpk', models.IntegerField()),
                ('cantidad', models.CharField(max_length=200)),
                ('vida', models.CharField(choices=[('Nueva', 'Nueva'), ('1R', '1R'), ('2R', '2R'), ('3R', '3R'), ('4R', '4R'), ('5R', '5R')], max_length=200)),
                ('calificacion', models.IntegerField()),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.compania')),
            ],
        ),
    ]
