# Generated by Django 4.0.3 on 2022-08-02 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0065_alter_presupuesto_compania_alter_presupuesto_mes_año_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presupuesto',
            old_name='mes_año',
            new_name='mes_ano',
        ),
    ]
