# Generated by Django 4.0.3 on 2022-08-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0066_rename_mes_año_presupuesto_mes_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='observacionLlanta'),
        ),
    ]
