# Generated by Django 4.0.3 on 2022-04-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0062_alter_vehiculo_clase'),
        ('dashboards', '0067_alter_tendenciacpk_cpk'),
    ]

    operations = [
    ]
