# Generated by Django 4.0.3 on 2022-04-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0069_inspeccion_presion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='observacion_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='observacion_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='observacion_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
