# Generated by Django 4.0.3 on 2022-08-06 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0069_tendencia_buena_presion_tendencia_correctas_pulpo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TendenciaAplicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('correctas_pulpo', models.FloatField()),
                ('inspecciones_a_tiempo', models.FloatField()),
                ('health', models.FloatField()),
                ('buena_presion', models.FloatField()),
                ('aplicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.aplicacion')),
                ('compania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.compania')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.ubicacion')),
            ],
        ),
    ]
