# Generated by Django 4.0.3 on 2022-04-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0070_inspeccion_observacion_1_inspeccion_observacion_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llanta',
            name='tirecheck',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tirecheck',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
