# Generated by Django 4.0.3 on 2022-04-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0071_llanta_tirecheck_vehiculo_tirecheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llanta',
            name='tirecheck',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='tirecheck',
        ),
    ]
