# Generated by Django 4.0.3 on 2022-08-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0071_tendenciaubicacion_tendenciacompania'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendimiento',
            name='year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
    ]
