# Generated by Django 4.0.3 on 2022-08-14 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0072_rendimiento_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='llanta',
            name='primera_inspeccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones_first', to='dashboards.inspeccion'),
        ),
    ]
