# Generated by Django 4.0.3 on 2022-04-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0072_remove_llanta_tirecheck_remove_vehiculo_tirecheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='llanta',
            name='tirecheck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tirecheck',
            field=models.BooleanField(default=False),
        ),
    ]
