# Generated by Django 4.0.3 on 2022-04-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0073_llanta_tirecheck_vehiculo_tirecheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='llanta',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
    ]
