# Generated by Django 4.0.3 on 2022-08-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0074_inspeccionvehiculo_tipo_de_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccionvehiculo',
            name='tipo_de_evento',
            field=models.CharField(choices=[('Inspección', 'Inspección'), ('Inspección Galgo', 'Inspección Galgo')], default='Inspección', max_length=1000),
        ),
    ]
