# Generated by Django 4.0.3 on 2022-04-07 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0074_llanta_archivado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='ultima_bitacora',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ultima_bitacora_pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras_pro', to='dashboards.bitacora_pro'),
        ),
    ]
