# Generated by Django 4.0.3 on 2022-08-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0075_alter_inspeccionvehiculo_tipo_de_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciollanta',
            name='km_desmontaje',
            field=models.IntegerField(null=True),
        ),
    ]
