# Generated by Django 4.0.3 on 2022-04-12 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0075_remove_vehiculo_ultima_bitacora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora_Edicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(max_length=500)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=500)),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.bitacora_edicion')),
            ],
        ),
    ]
