# Generated by Django 4.0.3 on 2022-04-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0076_bitacora_edicion_registro_bitacora'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='km',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
