# Generated by Django 4.0.3 on 2022-08-17 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0076_serviciollanta_km_desmontaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciollanta',
            name='eje',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciollanta',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboards.producto'),
        ),
        migrations.AddField(
            model_name='serviciollanta',
            name='tipo_de_eje',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
