# Generated by Django 4.0.3 on 2022-08-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0077_serviciollanta_eje_serviciollanta_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciollanta',
            name='nombre_de_eje',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
