# Generated by Django 4.0.3 on 2022-04-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0077_vehiculo_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='observacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
