# Generated by Django 4.0.3 on 2022-04-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0078_alter_vehiculo_clase_tendencia_status_and_more'),
        ('dashboards', '0078_vehiculo_observacion'),
    ]

    operations = [
    ]
