# Generated by Django 4.0.3 on 2022-08-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0078_serviciollanta_nombre_de_eje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciollanta',
            name='nombre_de_eje',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
