# Generated by Django 4.0.3 on 2022-08-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0079_alter_serviciollanta_nombre_de_eje'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendencia',
            name='correctas_inspeccion',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tendenciaaplicacion',
            name='correctas_inspeccion',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tendenciacompania',
            name='correctas_inspeccion',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tendenciaubicacion',
            name='correctas_inspeccion',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
