# Generated by Django 4.0.3 on 2022-04-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0080_remove_tendencia_status_compania_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compania',
            name='mm_de_desgaste_irregular',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='compania',
            name='mm_de_diferencia_entre_duales',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='compania',
            name='punto_retiro_eje_arrastre',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='compania',
            name='punto_retiro_eje_direccion',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='compania',
            name='punto_retiro_eje_loco',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='compania',
            name='punto_retiro_eje_retractil',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='compania',
            name='punto_retiro_eje_traccion',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='compania',
            name='valor_casco_1r',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compania',
            name='valor_casco_2r',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compania',
            name='valor_casco_3r',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compania',
            name='valor_casco_4r',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compania',
            name='valor_casco_5r',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compania',
            name='valor_casco_nuevo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
