# Generated by Django 4.0.3 on 2022-08-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0081_serviciovehiculo_hoja'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciovehiculo',
            name='hoja_vehiculo',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
