# Generated by Django 4.0.3 on 2022-04-15 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0081_alter_compania_mm_de_desgaste_irregular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacion',
            name='parametro_desgaste_arrastre',
            field=models.FloatField(default=3),
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='parametro_desgaste_direccion',
            field=models.FloatField(default=3),
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='parametro_desgaste_loco',
            field=models.FloatField(default=3),
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='parametro_desgaste_retractil',
            field=models.FloatField(default=3),
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='parametro_desgaste_traccion',
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name='producto',
            name='compania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.compania'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='profundidad_inicial',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='precio_nueva',
            field=models.FloatField(default=4000),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='precio_nueva_direccion',
            field=models.FloatField(default=5500),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='precio_renovada',
            field=models.FloatField(default=2000),
        ),
    ]
