# Generated by Django 4.0.3 on 2022-08-19 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0082_serviciovehiculo_hoja_vehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciovehiculo',
            name='hoja_vehiculo',
        ),
    ]
