# Generated by Django 4.0.3 on 2022-04-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0082_aplicacion_parametro_desgaste_arrastre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observacion',
            name='llanta',
        ),
        migrations.AddField(
            model_name='observacion',
            name='automatico',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='observacion',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='iconos'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='nivel',
            field=models.CharField(choices=[('Llanta', 'Llanta'), ('Vehiculo', 'Vehiculo')], default='llanta', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observacion',
            name='color',
            field=models.CharField(choices=[('Amarillo', 'Amarillo'), ('Rojo', 'Rojo'), ('NA', 'NA')], max_length=200),
        ),
    ]
