# Generated by Django 4.0.3 on 2022-04-15 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0083_remove_observacion_llanta_observacion_automatico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='presion_establecida',
            new_name='presion_establecida_1',
        ),
        migrations.RemoveField(
            model_name='desecho',
            name='llanta',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='observacion',
        ),
        migrations.AddField(
            model_name='desecho',
            name='compania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.compania'),
        ),
        migrations.AddField(
            model_name='renovador',
            name='compania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.compania'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='estatus_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='km_diario_maximo',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='observaciones',
            field=models.ManyToManyField(blank=True, null=True, to='dashboards.observacion'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='presion_establecida_2',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='presion_establecida_3',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='presion_establecida_4',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='presion_establecida_5',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='presion_establecida_6',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='presion_establecida_7',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
