# Generated by Django 4.0.3 on 2022-04-15 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0084_rename_presion_establecida_vehiculo_presion_establecida_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llanta',
            name='archivado',
        ),
        migrations.RemoveField(
            model_name='llanta',
            name='presion_establecida',
        ),
        migrations.AddField(
            model_name='llanta',
            name='aplicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.aplicacion'),
        ),
        migrations.AddField(
            model_name='llanta',
            name='fecha_de_entrada_inventario',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llanta',
            name='km_actual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llanta',
            name='observaciones',
            field=models.ManyToManyField(blank=True, limit_choices_to={'nivel': 'Llanta'}, null=True, to='dashboards.observacion'),
        ),
        migrations.AddField(
            model_name='llanta',
            name='presion_actual',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='llanta',
            name='profundidad_central',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llanta',
            name='profundidad_derecha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llanta',
            name='profundidad_izquierda',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llanta',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.taller'),
        ),
        migrations.AlterField(
            model_name='llanta',
            name='inventario',
            field=models.CharField(blank=True, choices=[('Nueva', 'Nueva'), ('Antes de Renovar', 'Antes de Renovar'), ('Antes de Desechar', 'Antes de Desechar'), ('Renovada', 'Renovada'), ('Con renovador', 'Con renovador'), ('Desecho final', 'Desecho final'), ('Servicio', 'Servicio'), ('Rodante', 'Rodante'), ('Archivado', 'Archivado')], default='Rodante', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='observaciones',
            field=models.ManyToManyField(blank=True, limit_choices_to={'nivel': 'Vehiculo'}, null=True, to='dashboards.observacion'),
        ),
    ]
