# Generated by Django 4.0.3 on 2022-08-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0086_tendenciaaplicacion_pulpos_a_tiempo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='estado',
            field=models.CharField(default='Buena', max_length=255),
        ),
        migrations.AddField(
            model_name='bitacora_pro',
            name='estado',
            field=models.CharField(default='Buena', max_length=255),
        ),
    ]
