# Generated by Django 4.0.3 on 2022-04-17 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0086_remove_inspeccion_max_profundidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoLlanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_recorrido_nuevo', models.IntegerField()),
                ('km_recorrido_1', models.IntegerField()),
                ('km_recorrido_2', models.IntegerField()),
                ('km_recorrido_3', models.IntegerField()),
                ('km_recorrido_4', models.IntegerField()),
                ('km_recorrido_5', models.IntegerField()),
                ('km_total', models.IntegerField()),
                ('casco_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casco_nuevo', to='dashboards.producto')),
                ('num_eco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.llanta')),
                ('renovado_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovado_1', to='dashboards.producto')),
                ('renovado_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovado_2', to='dashboards.producto')),
                ('renovado_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovado_3', to='dashboards.producto')),
                ('renovado_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovado_4', to='dashboards.producto')),
                ('renovado_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovado_5', to='dashboards.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('horario_programada', models.TimeField()),
                ('fecha_real', models.DateField(blank=True, null=True)),
                ('horario_real', models.TimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboards.perfil')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='TareasServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(choices=[('Prueba', 'Prueba')], max_length=200)),
                ('posicion_llanta_1', models.CharField(max_length=200)),
                ('posicion_llanta_2', models.CharField(max_length=200)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.servicio')),
                ('llanta_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llanta_1', to='dashboards.llanta')),
                ('llanta_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llanta_2', to='dashboards.llanta')),
                ('vehiculo_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo_1', to='dashboards.vehiculo')),
                ('vehiculo_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo_2', to='dashboards.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Tendencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField()),
                ('posicion', models.CharField(max_length=200)),
                ('nombre_de_eje', models.CharField(blank=True, choices=[('Dirección', 'Dirección'), ('Tracción', 'Tracción'), ('Arrastre', 'Arrastre'), ('Loco', 'Loco'), ('Retractil', 'Retractil')], max_length=200, null=True)),
                ('km', models.IntegerField()),
                ('km_proyectado', models.IntegerField()),
                ('cpk', models.FloatField()),
                ('min_profundidad', models.FloatField()),
                ('color', models.CharField(choices=[('Amarillo', 'Amarillo'), ('Rojo', 'Rojo'), ('NA', 'NA')], max_length=200)),
                ('buena_presion', models.BooleanField()),
                ('vida', models.CharField(blank=True, choices=[('Nueva', 'Nueva'), ('1R', '1R'), ('2R', '2R'), ('3R', '3R'), ('4R', '4R'), ('5R', '5R')], max_length=200, null=True)),
                ('calificacion', models.IntegerField()),
                ('salud', models.BooleanField()),
                ('aplicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboards.aplicacion')),
                ('llanta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.llanta')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboards.producto')),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboards.ubicacion')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.vehiculo')),
            ],
        ),
        migrations.RemoveField(
            model_name='registro_bitacora',
            name='bitacora',
        ),
        migrations.RemoveField(
            model_name='tendenciacpk',
            name='compania',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='presion_establecida',
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='edicion_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='evento',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='tipo_de_evento',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='Bitacora_Edicion',
        ),
        migrations.DeleteModel(
            name='Registro_Bitacora',
        ),
        migrations.DeleteModel(
            name='TendenciaCPK',
        ),
    ]
