# Generated by Django 4.0.3 on 2022-08-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0087_bitacora_estado_bitacora_pro_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendesecho',
            name='imagen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
