# Generated by Django 4.0.3 on 2022-04-17 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0088_llanta_desecho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llanta',
            name='compania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.compania'),
        ),
    ]
