# Generated by Django 4.0.3 on 2022-04-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0090_alter_inspeccion_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccion',
            name='tipo_de_evento',
            field=models.CharField(choices=[('Inspección', 'Inspección'), ('Inspección Galgo', 'Inspección Galgo')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='clase',
            field=models.CharField(blank=True, choices=[('ARRASTRE', 'Arrastre'), ('TRUCK - BOX', 'Truck - Box'), ('VAN', 'Van'), ('TRAILER - FLAT BED', 'Trailer - Flat Bed'), ('RAMPLA PLANA', 'Rampla Plana'), ('RAMPLA PLANA', 'Rampla Plana'), ('RAMPLA PLANA', 'Rampla Plana'), ('TRAILER - DUMP', 'Trailer - Dump'), ('TRAILER - DUMP', 'Trailer - Dump'), ('TRAILER - DUMP', 'Trailer - Dump'), ('TRUCK', 'Truck'), ('CONTAINER CARRIER CHASSIS', 'Container Carrier Chassis'), ('CONTAINER CARRIER CHASSIS', 'Container Carrier Chassis'), ('CONTAINER CARRIER CHASSIS', 'Container Carrier Chassis'), ('GONDOLA', 'Gondola'), ('GONDOLA', 'Gondola'), ('GONDOLA', 'Gondola'), ('GONDOLA', 'Gondola'), ('GONDOLA', 'Gondola'), ('GONDOLA', 'Gondola'), ('GONDOLA', 'Gondola'), ('GONDOLA', 'Gondola'), ('GONDOLA', 'Gondola'), ('GONDOLA', 'Gondola'), ('GONDOLA', 'Gondola'), ('GONDOLA', 'Gondola'), ('GONDOLA', 'Gondola'), ('GONDOLA', 'Gondola'), ('GONDOLA', 'Gondola'), ('GONDOLA', 'Gondola'), ('GONDOLA', 'Gondola'), ('GONDOLA', 'Gondola'), ('GONDOLA', 'Gondola'), ('GONDOLA', 'Gondola'), ('GONDOLA', 'Gondola'), ('TRACTOR - SLEEPER', 'Tractor - Sleeper'), ('TRUCK - DUMP', 'Truck - Dump'), ('TRAILER', 'Trailer'), ('AUTOBUS', 'Autobus'), ('AUTOMOVIL', 'Automovil'), ('AUTOTANQUE ALIMENTICIO', 'Autotanque Alimenticio'), ('AUTOTANQUE COMBUSTIBLE', 'Autotanque Combustible'), ('AUTOTANQUE QUIMICOS', 'Autotanque Químicos'), ('CAJA REFRIGERADO 48', 'Caja Refrigerado 48'), ('CAJA SECA', 'Caja Seca'), ('CAJA SECA 40', 'Caja Seca 40'), ('CAJA SECA 48', 'Caja Seca 48'), ('CAJA SECA 53', 'Caja Seca 53'), ('CAJA SECA 53 (3 EJES)', 'Caja Seca 53 (3 Ejes)'), ('CAMIÓN', 'Camión'), ('CAMIÓN - CAMAROTE', 'Camión - Camarote'), ('CAMIONETA', 'Camioneta'), ('CAMIONETA LIGERA', 'Camioneta ligera'), ('CORTINA', 'Cortina'), ('CORTINA 38', 'Cortina 38'), ('DOLLY', 'Dolly'), ('MOTOCICLETA', 'Motocicleta'), ('PICK-UP', 'Pick-Up'), ('PLATAFORMA 35', 'Plataforma 35'), ('PLATAFORMA 40', 'Plataforma 40'), ('PLATAFORMA 53', 'Plataforma 53'), ('PLATAFORMA 53 (3 EJES)', 'Plataforma 53 (3 Ejes)'), ('PORTACONTENEDOR', 'Portacontenedor'), ('RABON', 'Rabon'), ('REMOLQUE', 'Remolque'), ('REMOLQUE - CAJA SECA', 'Remolque - Caja Seca'), ('THERMOKING THORTON CAJA 25', 'Thermoking Thorton Caja 25'), ('TOLVA', 'Tolva'), ('TORTHON', 'Torthon'), ('TORTHON REFRIGERADO', 'Torthon Refrigerado'), ('TORTHON SECO', 'Torthon Seco'), ('TRACTOR', 'Tractor'), ('TRACTOCAMION', 'Tractocamion'), ('UTILITARIO TALLER', 'Utilitario Taller'), ('UTILITARIO ADMINISTRATIVO', 'Utilitario Administrativo'), ('YARD TRUCK', 'Yard Truck')], max_length=200, null=True),
        ),
    ]
