# Generated by Django 4.0.3 on 2022-04-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0092_rename_km_inspeccion_km_vehiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='nuevo',
            field=models.BooleanField(default=False),
        ),
    ]
