# Generated by Django 4.0.3 on 2022-04-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0093_vehiculo_nuevo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llanta',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='presion_establecida_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='presion_establecida_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='presion_establecida_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='presion_establecida_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='presion_establecida_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='presion_establecida_6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='presion_establecida_7',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
