# Generated by Django 4.0.2 on 2022-04-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0094_remove_llanta_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccion',
            name='observaciones',
            field=models.ManyToManyField(blank=True, limit_choices_to={'nivel': 'Llanta'}, null=True, to='dashboards.Observacion'),
        ),
        migrations.AlterField(
            model_name='llanta',
            name='observaciones',
            field=models.ManyToManyField(blank=True, limit_choices_to={'nivel': 'Llanta'}, null=True, to='dashboards.Observacion'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='observaciones',
            field=models.ManyToManyField(blank=True, limit_choices_to={'nivel': 'Vehiculo'}, null=True, to='dashboards.Observacion'),
        ),
    ]
