# Generated by Django 4.0.3 on 2022-04-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0095_alter_inspeccion_observaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
