# Generated by Django 4.0.3 on 2022-04-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0096_ubicacion_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccion',
            name='fecha_hora',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
