# Generated by Django 4.0.3 on 2022-04-27 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0097_alter_inspeccion_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicollanta',
            name='casco_nuevo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casco_nuevo', to='dashboards.producto'),
        ),
        migrations.AlterField(
            model_name='historicollanta',
            name='km_recorrido_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicollanta',
            name='km_recorrido_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicollanta',
            name='km_recorrido_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicollanta',
            name='km_recorrido_4',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicollanta',
            name='km_recorrido_5',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicollanta',
            name='km_recorrido_nuevo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicollanta',
            name='km_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicollanta',
            name='renovado_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renovado_1', to='dashboards.producto'),
        ),
        migrations.AlterField(
            model_name='historicollanta',
            name='renovado_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renovado_2', to='dashboards.producto'),
        ),
        migrations.AlterField(
            model_name='historicollanta',
            name='renovado_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renovado_3', to='dashboards.producto'),
        ),
        migrations.AlterField(
            model_name='historicollanta',
            name='renovado_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renovado_4', to='dashboards.producto'),
        ),
        migrations.AlterField(
            model_name='historicollanta',
            name='renovado_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renovado_5', to='dashboards.producto'),
        ),
    ]
