# Generated by Django 4.0.3 on 2022-04-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0098_alter_historicollanta_casco_nuevo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='icono',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
