# Generated by Django 4.0.3 on 2022-04-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0099_alter_observacion_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccion',
            name='km_vehiculo',
            field=models.IntegerField(default=1000, null=True),
        ),
    ]
