# Generated by Django 4.0.3 on 2022-04-30 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0098_alter_inspeccion_km_vehiculo_alter_vehiculo_clase'),
        ('dashboards', '0100_alter_inspeccion_km_vehiculo'),
    ]

    operations = [
    ]
