# Generated by Django 4.0.3 on 2022-05-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0101_merge_20220502_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='recomendacion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='clase',
            field=models.CharField(blank=True, choices=[('ARRASTRE', 'Arrastre'), ('TRUCK - BOX', 'Truck - Box'), ('VAN', 'Van'), ('TRAILER - FLAT BED', 'Trailer - Flat Bed'), ('CÁMARA FRIGORÍFICA', 'Cámara Frigorífica'), ('COACH', 'Coach'), ('TRAILER - DUMP', 'Trailer - Dump'), ('RAMPLA PLANA', 'Rampla Plana'), ('TRAILER - DUMP', 'Trailer - Dump'), ('GONDOLA', 'Gondola'), ('TRACTOR - SLEEPER', 'Tractor - Sleeper'), ('TRUCK - DUMP', 'Truck - Dump'), ('TRAILER', 'Trailer'), ('AUTOBUS', 'Autobus'), ('AUTOMOVIL', 'Automovil'), ('AUTOTANQUE ALIMENTICIO', 'Autotanque Alimenticio'), ('AUTOTANQUE COMBUSTIBLE', 'Autotanque Combustible'), ('AUTOTANQUE QUIMICOS', 'Autotanque Químicos'), ('CAJA REFRIGERADO 48', 'Caja Refrigerado 48'), ('CAJA SECA', 'Caja Seca'), ('CAJA SECA 40', 'Caja Seca 40'), ('CAJA SECA 48', 'Caja Seca 48'), ('CAJA SECA 53', 'Caja Seca 53'), ('CAJA SECA 53 (3 EJES)', 'Caja Seca 53 (3 Ejes)'), ('CAMIÓN', 'Camión'), ('CAMIÓN - CAMAROTE', 'Camión - Camarote'), ('CAMIONETA', 'Camioneta'), ('CAMIONETA LIGERA', 'Camioneta ligera'), ('CORTINA', 'Cortina'), ('CORTINA 38', 'Cortina 38'), ('DOLLY', 'Dolly'), ('MOTOCICLETA', 'Motocicleta'), ('PICK-UP', 'Pick-Up'), ('PLATAFORMA 35', 'Plataforma 35'), ('PLATAFORMA 40', 'Plataforma 40'), ('PLATAFORMA 53', 'Plataforma 53'), ('PLATAFORMA 53 (3 EJES)', 'Plataforma 53 (3 Ejes)'), ('PORTACONTENEDOR', 'Portacontenedor'), ('RABON', 'Rabon'), ('REMOLQUE', 'Remolque'), ('REMOLQUE - CAJA SECA', 'Remolque - Caja Seca'), ('THERMOKING THORTON CAJA 25', 'Thermoking Thorton Caja 25'), ('TOLVA', 'Tolva'), ('TORTHON', 'Torthon'), ('TORTHON REFRIGERADO', 'Torthon Refrigerado'), ('TORTHON SECO', 'Torthon Seco'), ('TRACTOR', 'Tractor'), ('TRACTOCAMION', 'Tractocamion'), ('UTILITARIO TALLER', 'Utilitario Taller'), ('UTILITARIO ADMINISTRATIVO', 'Utilitario Administrativo'), ('YARD TRUCK', 'Yard Truck')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='configuracion',
            field=models.CharField(blank=True, choices=[('S1.D1', 'S1.D1'), ('S2.D2', 'S2.D2'), ('S2.D2.D2', 'S2.D2.D2'), ('S2.D2.D2.T4.T4', 'S2.D2.D2.T4.T4'), ('S2.C4.D4', 'S2.C4.D4'), ('S2.D4', 'S2.D4'), ('S2.D4.SP1', 'S2.D4.SP1'), ('S2.D4.C4.SP1', 'S2.D4.C4.SP1'), ('S2.D4.D4', 'S2.D4.D4'), ('S2.D4.D4.D4', 'S2.D4.D4.D4'), ('S2.D4.D4.L2', 'S2.D4.D4.L2'), ('S2.D4.D4.SP1', 'S2.D4.D4.SP1'), ('S2.D4.D4.T4.T4', 'S2.D4.D4.T4.T4'), ('S2.D4.L4', 'S2.D4.L4'), ('S2.S2.D4', 'S2.S2.D4'), ('S2.L2.D4', 'S2.L2.D4'), ('S2.L2.D4.D4', 'S2.L2.D4.D4'), ('S2.L2.D4.D4.D2', 'S2.L2.D4.D4.D2'), ('S2.L2.D4.D4.L2', 'S2.L2.D4.D4.L2'), ('S2.L2.D4.D4.L4', 'S2.L2.D4.D4.L4'), ('S2.L2.L2.D4.D4', 'S2.L2.L2.D4.D4'), ('S2.L2.L2.D4.D4.L2', 'S2.L2.L2.D4.D4.L2'), ('S2.L2.L2.L2.D4.D4', 'S2.L2.L2.L2.D4.D4'), ('S2.L2.L2.L2.L2.D4.D4', 'S2.L2.L2.L2.L2.D4.D4'), ('S2.L4.D4', 'S2.L4.D4'), ('S2.L4.D4.D4', 'S2.L4.D4.D4'), ('T4.T4', 'T4.T4'), ('T4.T4.T4', 'T4.T4.T4'), ('T4.T4.SP1', 'T4.T4.SP1'), ('T4.T4.SP2', 'T4.T4.SP2'), ('T4.T4.T4.SP2', 'T4.T4.T4.SP2')], max_length=200, null=True),
        ),
    ]
