# Generated by Django 4.0.3 on 2022-05-03 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0102_observacion_recomendacion_alter_vehiculo_clase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llanta',
            name='ultima_inspeccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones', to='dashboards.inspeccion'),
        ),
    ]
