# Generated by Django 4.0.3 on 2022-05-03 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0103_alter_llanta_ultima_inspeccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspeccionVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True, null=True)),
                ('observaciones', models.ManyToManyField(blank=True, limit_choices_to={'nivel': 'Vehiculo'}, null=True, to='dashboards.observacion')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.vehiculo')),
            ],
        ),
    ]
