# Generated by Django 4.0.3 on 2022-05-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0105_inspeccion_inspeccion_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='km',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
