# Generated by Django 4.0.3 on 2022-05-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0106_inspeccionvehiculo_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='posicion',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
