# Generated by Django 4.0.3 on 2022-05-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0107_inspeccion_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='tipo_de_eje',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
