# Generated by Django 4.0.3 on 2022-05-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0108_inspeccion_tipo_de_eje'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='eje',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
