# Generated by Django 4.0.3 on 2022-05-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0101_merge_20220430_1817'),
        ('dashboards', '0109_inspeccion_eje'),
    ]

    operations = [
    ]
