# Generated by Django 4.0.3 on 2022-05-04 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0109_inspeccion_eje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observacion',
            name='recomendacion',
        ),
    ]
