# Generated by Django 4.0.3 on 2022-05-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0110_merge_0101_merge_20220430_1817_0109_inspeccion_eje'),
        ('dashboards', '0110_remove_observacion_recomendacion'),
    ]

    operations = [
    ]
