# Generated by Django 4.0.3 on 2022-05-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0111_merge_20220505_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='recomendacion',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
