# Generated by Django 4.0.2 on 2022-05-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0111_merge_20220505_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccionvehiculo',
            name='observaciones',
            field=models.ManyToManyField(blank=True, limit_choices_to={'nivel': 'Vehiculo'}, null=True, to='dashboards.Observacion'),
        ),
    ]
