# Generated by Django 4.0.3 on 2022-05-06 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0112_alter_inspeccionvehiculo_observaciones'),
        ('dashboards', '0113_alter_vehiculo_configuracion'),
    ]

    operations = [
    ]
