# Generated by Django 4.0.3 on 2022-05-06 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0115_remove_observacion_recomendacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='ultima_inspeccion',
        ),
    ]
