client_config_backend: settings
client_config:
  client_id: 1025165674048-eh1ns4l5iea1jdkcbleqkob3ihvug9ll.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials_module.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive