client_config_backend: settings
client_config:
  client_id: 395869238662-7s59rgpbj22fqan9bgtui76qp4k7hg9l.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials_module.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive