# Generated by Django 4.0.3 on 2022-07-01 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0035_alter_bitacora_desecho_options_rendimiento'),
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='compania',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboards.compania'),
            preserve_default=False,
        ),
    ]
