# Generated by Django 4.0.3 on 2022-07-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_calendario_compania'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='horario_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendario',
            name='horario_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
