# Generated by Django 4.0.3 on 2022-07-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_calendario_servicio_calendario_vehiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='horario_end_str',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calendario',
            name='horario_start_str',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
