# Generated by Django 4.0.3 on 2022-07-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0005_calendario_horario_end_str_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario',
            name='horario_end',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='horario_start',
        ),
        migrations.AlterField(
            model_name='calendario',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
