# Generated by Django 4.0.3 on 2022-07-14 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0006_remove_calendario_horario_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendario',
            old_name='title',
            new_name='title_current',
        ),
    ]
