// Generated by https://quicktype.io

/*
 * IMPORTANT
 * DON'T USE EXPORT OR IMPORT
 */

interface RotarResponse {
  pagination: Pagination;
  vehiculos_list: VehiculosList[];
  llantas: Llanta[];
  km_max: string;
  km_min: string;
}

interface Llanta {
  numero_economico: string;
  id: number;
  posicion: string;
}

interface Pagination {
  prev: null;
  next: string;
}

interface VehiculosList {
  id: number;
  numero_economico: string;
}

interface Servicio {
  almacen_desmontaje: string;
  balancear: string;
  costado: string;
  destino_llanta: string;
  id_servicio: string;
  inflar: string;
  llantaId: string;
  llantaOrigen: string;
  nuevaLlanta: string;
  numero_economico: string;
  otroVehiculo: string;
  posicion: string;
  razon: string;
  reparar: string;
  rotar: string;
  stock: string;
  taller_desmontaje: string;
  tipoServicio: string;
  valvula: string;
}

// ? Utilidades

const getSelectInputs = (id: string) => {
  const views = Array(...document.querySelectorAll(`[data-view="${id}"]`)),
    servicios = Array(
      ...views[0].querySelectorAll<HTMLInputElement>('input, select')
    ),
    montajes = Array(
      ...views[1].querySelectorAll<HTMLInputElement>('input, select')
    );
  const isVehicle = servicios.some(
    (input) => input.value === 'mismo' && input.checked === true
  );
  const isOtherVehicle = servicios.some(
    (input) => input.value === 'otro' && input.checked === true
  );

  const totalServicios = servicios.filter((item) => {
    if (item.checked === true) {
      return item;
    }

    if (item.type !== 'checkbox' && item.type !== 'radio') {
      if (item.value) return item;
    }
  });
  const totalMontajes = montajes.filter((item) => {
    if (item.checked === true) {
      return item;
    }

    if (item.type !== 'checkbox' && item.type !== 'radio') {
      if (item.value) return item;
    }
  });

  return {
    totalMontajes,
    totalServicios,
    servicios,
    montajes,
    isVehicle,
    isOtherVehicle,
  };
};

// * Add KM on load page

(() => {
  document.addEventListener('DOMContentLoaded', (e) => {
    const form: HTMLFormElement = document.querySelector(
      '.service-page'
    ) as HTMLFormElement;
    const data = Object.fromEntries(new FormData(form));

    const formHidden = document.getElementById(
      'hoja-servicio'
    ) as unknown as HTMLInputElement;
    formHidden.value = JSON.stringify(data);
  });
})();

// * Modal

(() => {
  const tires = document.querySelectorAll('.tire');

  tires.forEach((tire) => {
    tire.addEventListener('click', (e) => {
      let tireTs = tire as unknown as HTMLInputElement;
      const id: string | undefined = tireTs.dataset.id;

      const modal = document.querySelector(`[data-modal="${id}"]`);
      modal?.classList.add('active');

      document.addEventListener('click', (e) => {
        const target = e.target as HTMLElement;
        if (target.matches('.close-modal')) {
          modal?.classList.remove('active');
        }
      });
    });
  });
})();

// * Manejo de información

(() => {
  let saveData: any[] = [];

  /*
   * Methods
   */

  const eventList = document.querySelector('.tire-list') as HTMLElement;
  const formHidden = document.getElementById(
    'data-taller'
  ) as unknown as HTMLInputElement;

  const addEvent = (servicio: Servicio) => {
    eventList.insertAdjacentHTML(
      'afterbegin',
      `
    <div class="tire-item" data-servicioid="${servicio.id_servicio}" >
        <span class="delete" data-delete="${
          servicio.id_servicio
        }" data-tireown="${servicio.llantaId}">
            &times;
          </span>
          <div class="service__img">
            <span class="icon-llanta-outline"></span>
          </div>
          <div class="service__body">
          ${
            servicio.tipoServicio === 'desmontaje'
              ? `
              <h3 class="service__title">
              Desmontaje
            </h3>
          `
              : ''
          }
              ${
                servicio.inflar !== ''
                  ? `
              <h3 class="service__title">
                Inflado
              </h3>
              `
                  : ''
              }
              ${
                servicio.rotar === 'otro'
                  ? `
              <h3 class="service__title">
                Rotación entre vehículos
              </h3>
              `
                  : ''
              }
              ${
                servicio.rotar === 'mismo'
                  ? `
              <h3 class="service__title">
                Rotación entre llantas
              </h3>
              `
                  : ''
              }
              ${
                servicio.balancear !== ''
                  ? `
              <h3 class="service__title">
              Balanceo
            </h3>
              `
                  : ''
              }
              ${
                servicio.reparar !== ''
                  ? `
              <h3 class="service__title">
                Reparación
              </h3>
              `
                  : ''
              }
              ${
                servicio.valvula !== ''
                  ? `
              <h3 class="service__title">
                Reparación de valvula
              </h3>
              `
                  : ''
              }
              ${
                servicio.costado !== ''
                  ? `
              <h3 class="service__title">
                Reparación de costado
              </h3>
              `
                  : ''
              }
            <p><strong>Llanta:</strong> ${servicio.numero_economico}</p>
            <p><strong>Posición:</strong> ${servicio.posicion}</p>
            ${
              servicio.razon.length >= 1
                ? `
            <p>
              <strong>Razón de desmontaje:</strong> 
              ${servicio.razon}
            </p>
            `
                : ''
            }
            ${
              servicio.otroVehiculo.length >= 1
                ? `
            <p>
              <strong>Vehículo Destino:</strong> 
              ${servicio.otroVehiculo}
            </p>
            `
                : ''
            }
            ${
              servicio.destino_llanta
                ? `
              <p>
                <strong>Llanta y Posición Destino:</strong> 
                ${servicio.destino_llanta}
              </p>
              `
                : ''
            }
            ${
              servicio.nuevaLlanta.length >= 1
                ? `<p><strong>Nueva llanta</strong>: ${servicio.nuevaLlanta}</p>`
                : ''
            }
            ${
              servicio.stock.length >= 1
                ? `<p><strong>Stock origen</strong>: ${servicio.stock}</p>`
                : ''
            }
            ${
              servicio.almacen_desmontaje.length >= 1
                ? `<p><strong>Stock destino</strong>: ${servicio.almacen_desmontaje}</p>`
                : ''
            }
          </div>
      </div>
      `
    );
  };

  type DeleteEvent = {
    serviceId: string | undefined;
    tireId: string | undefined;
  };

  const deleteEvent = ({ serviceId, tireId }: DeleteEvent) => {
    if (serviceId === undefined || tireId === undefined) return;

    const card = document.querySelector(
      `[data-servicioid="${serviceId}"]`
    ) as HTMLDivElement;
    const modal = document.querySelector(
      `[data-modal="${tireId}"] form`
    ) as HTMLDivElement;

    // * Clean
    saveData = saveData.filter((item) => item.id_servicio !== serviceId);
    card?.remove();
    modal
      ?.querySelectorAll<HTMLSelectElement | HTMLInputElement>(
        'input, select, button'
      )
      .forEach((item) => {
        item.disabled = false;
      });

    modal
      ?.querySelectorAll<HTMLInputElement>('.form__services input')
      .forEach((item) => {
        item.checked = false;
      });

    modal
      ?.querySelectorAll<HTMLInputElement>('.card__config-modal input')
      .forEach((item) => {
        if (item.type === 'radio') {
          item.checked = false;
        }
        const tires = document.querySelector(
          `[data-rotar-id="${tireId}"] input[value="${tireId}"]`
        ) as HTMLInputElement;
        tires.disabled = true;
      });

    modal
      ?.querySelectorAll<HTMLSelectElement>('.form__view-body select')
      .forEach((item) => {
        item.value = '';
      });

    formHidden.value = JSON.stringify(saveData);
  };

  // * Events

  document.addEventListener('submit', (e) => {
    const target = e.target as HTMLFormElement;

    if (target.matches('#taller-form')) {
      const date = document.querySelector(
          'input[type="date"]'
        ) as unknown as HTMLInputElement,
        time = document.querySelector(
          'input[type="time"]'
        ) as unknown as HTMLInputElement,
        user = document.querySelector(
          'select[name="usuario"]'
        ) as unknown as HTMLInputElement,
        km = document.querySelector(
          'input[name="km_montado"]'
        ) as unknown as HTMLInputElement,
        noKm = document.querySelector(
          'input[name="no_km"]'
        ) as unknown as HTMLInputElement;

      if (date.value === '' || time.value === '' || user.value === '') {
        e.preventDefault();
        Swal.fire(
          'Error',
          'No se han completado datos en la hoja de servicio',
          'error'
        );
        return;
      }

      if (km.value === '' && !noKm.checked) {
        e.preventDefault();
        Swal.fire('Error', 'No se ha puesto un KM de montado', 'error');
        return;
      }

      return;
    }

    if (target.matches('.service-page')) {
      e.preventDefault();
      const form: HTMLFormElement = e.target as HTMLFormElement;
      const data = Object.fromEntries(new FormData(form));

      const formHidden = document.getElementById(
        'hoja-servicio'
      ) as unknown as HTMLInputElement;
      formHidden.value = JSON.stringify(data);

      document
        .querySelector('.alert__success')
        ?.classList.add('active') as unknown as HTMLDivElement;

      setTimeout(
        () =>
          document.querySelector('.alert__success')?.classList.remove('active'),
        2000
      );
      return;
    }

    e.preventDefault(); // prevenimos el evento

    const form: HTMLFormElement = e.target as HTMLFormElement;
    const dataForm = new FormData(form);
    dataForm.append('id_servicio', String(Math.floor(Math.random() * 10000)));
    const data = Object.fromEntries(dataForm) as unknown as Servicio;
    const formContainer = form.parentElement;
    const {
      totalMontajes,
      totalServicios,
      montajes,
      isVehicle,
      isOtherVehicle,
    } = getSelectInputs(form.parentElement?.dataset.modal!);

    const otroVehiculo = form.querySelector('.otro-vehiculo'),
      ovInputs = Array(
        ...otroVehiculo?.querySelectorAll<HTMLInputElement & HTMLSelectElement>(
          'input, select'
        )!
      ).filter((item) => item.type !== 'hidden');

    const imposibleKm = ovInputs.find(
      (input) => input.name === 'no_km' && input.checked === true
    );

    let rotarIsComplete: boolean | null = true;

    if (ovInputs[0].value) {
      if (!imposibleKm) {
        rotarIsComplete = ovInputs.some((input) => !input.value);
      } else {
        ovInputs[1].value
          ? (rotarIsComplete = false)
          : (rotarIsComplete = true);
      }
    }

    if (isVehicle) {
      let inputs = Array(
          ...form.querySelectorAll<HTMLInputElement>(
            '.card__config-modal input'
          )
        ),
        isSelectInput = inputs.some((input) => input.checked === true);

      if (!isSelectInput) {
        return Swal.fire(
          'Rotación incompleta',
          'Seleccione una llanta para completar la rotación',
          'warning'
        );
      }
    }

    if (isOtherVehicle) {
      if (rotarIsComplete) {
        return Swal.fire(
          'Algo anda mal',
          'Faltan datos para completar la rotación',
          'warning'
        );
      }
    }

    // if (input.name === 'kmMontadoOtro' && !imposibleKm) {
    //   return Swal.fire(
    //     'Los datos estan incompletos',
    //     'Por favor complete todos los datos de rotación',
    //     'warning'
    //   );
    // }

    if (totalMontajes.length === 0 && totalServicios.length <= 1) {
      return Swal.fire(
        'Ups, no se ha realizado nada',
        'No puede guardar si no ha realizado un servicio',
        'error'
      );
    }

    if (totalMontajes.length > 0) {
      if (totalMontajes.length < montajes.length) {
        return Swal.fire(
          'Montaje incompleto',
          'El montaje no se ha completado',
          'warning'
        );
      }
    }

    addEvent(data);

    form
      .querySelectorAll<HTMLInputElement>('input, select, .btn-taller')
      .forEach((input) => (input.disabled = true));

    saveData.push(data);

    formHidden.value = JSON.stringify(saveData);

    formContainer?.classList.remove('active');

    document
      .querySelector('.alert__success')
      ?.classList.add('active') as unknown as HTMLDivElement;

    setTimeout(
      () =>
        document.querySelector('.alert__success')?.classList.remove('active'),
      2000
    );
  });

  document.addEventListener('change', (e) => {
    const target = e.target as HTMLInputElement;

    if (target.matches('#no_km')) {
      const kmInput = document.querySelector(
        '[name="km_montado"]'
      ) as HTMLInputElement;
      if (target.checked) {
        kmInput.disabled = true;
      } else {
        kmInput.disabled = false;
      }
    }

    if (
      target.type === 'date' ||
      target.type === 'time' ||
      target.name === 'usuario'
    ) {
      const form = document.querySelector('.service-page') as HTMLFormElement;
      const data = Object.fromEntries(new FormData(form));

      const formHidden = document.getElementById(
        'hoja-servicio'
      ) as unknown as HTMLInputElement;
      formHidden.value = JSON.stringify(data);

      document
        .querySelector('.alert__success')
        ?.classList.add('active') as unknown as HTMLDivElement;

      setTimeout(
        () =>
          document.querySelector('.alert__success')?.classList.remove('active'),
        2000
      );
    }

    if (target.matches('[data-vehicleFix]')) {
      const formHidden = document.getElementById(
        'vehiculo-data'
      ) as unknown as HTMLInputElement;

      const form = document.getElementById('vehicle-form') as HTMLFormElement;
      const formData = Object.fromEntries(new FormData(form));

      if (target.checked) {
        target.value = 'on';
      } else {
        target.value = '';
      }

      formHidden.value = JSON.stringify(formData);
    }

    if (target.name === 'rotar') {
      const container = document.querySelectorAll<HTMLDivElement>(
        `[data-rotar-id="${target.dataset.radioid}"]`
      );
      switch (target.value) {
        case 'no':
          document
            .querySelectorAll<HTMLInputElement>(
              `[data-rotar-id="${target.dataset.radioid}"]`
            )
            .forEach((label) => (label.style.display = 'none'));

          container[0]
            .querySelectorAll<HTMLInputElement>('input, select')
            .forEach((input) => (input.value = ''));
          container[1]
            .querySelectorAll<HTMLInputElement>('input, select')
            .forEach((input) => (input.checked = false));
          break;

        case 'mismo':
          container[0].style.display = 'none';
          container[1].style.display = 'flex';

          container[0]
            .querySelectorAll<HTMLInputElement>('input, select')
            .forEach((input) => (input.value = ''));
          break;

        case 'otro':
          container[0].style.display = 'block';
          container[1].style.display = 'none';
          container[1]
            .querySelectorAll<HTMLInputElement>('input')
            .forEach((input) => (input.checked = false));
          break;

        default:
          break;
      }
    }

    if (target.dataset.nav) {
      if (target.value === 'desmontaje') {
        document
          .querySelectorAll(`[data-view="${target.dataset.nav}"]`)
          .forEach((item) => item.classList.remove('active'));

        target.classList.add('active');
        document
          .querySelectorAll<HTMLDivElement>(
            `[data-view="${target.dataset.nav}"]`
          )
          .forEach((view) => (view.style.display = 'none'));

        document.querySelectorAll<HTMLDivElement>(
          `[data-view="${target.dataset.nav}"]`
        )[1].style.display = 'block';
      } else {
        document
          .querySelectorAll<HTMLDivElement>(
            `[data-view="${target.dataset.nav}"]`
          )
          .forEach((item) => item.classList.remove('active'));

        target.classList.add('active');
        document
          .querySelectorAll<HTMLDivElement>(
            `[data-view="${target.dataset.nav}"]`
          )
          .forEach((view) => (view.style.display = 'none'));

        document.querySelectorAll<HTMLDivElement>(
          `[data-view="${target.dataset.nav}"]`
        )[0].style.display = 'block';
      }
    }
  });

  document.addEventListener('input', (e) => {
    const target = e.target as HTMLInputElement;

    const form = document.querySelector('.service-page') as HTMLFormElement;
    const data = Object.fromEntries(new FormData(form));

    const formHidden = document.getElementById(
      'hoja-servicio'
    ) as unknown as HTMLInputElement;
    formHidden.value = JSON.stringify(data);
  });

  // * Eliminar evento
  document.addEventListener('click', (e) => {
    const event = e.target as HTMLElement;

    if (event.matches('.delete')) {
      deleteEvent({
        serviceId: event.dataset.delete,
        tireId: event.dataset.tireown,
      });
    }
  });
})();

// * Montaje

(() => {
  document.addEventListener('change', (e) => {
    const target = e.target as HTMLInputElement;

    if (target.name === 'stock') {
      const llanta = target.nextElementSibling
        ?.nextElementSibling as HTMLInputElement;

      switch (target.value) {
        case 'nueva':
          fetch('/api/tiresearchtaller?inventario=Nueva')
            .then((res) => res.json())
            .then((json) => {
              let options = '';

              json.result.forEach((item: any) => {
                options += `<option value="${item.numero_economico}">${item.numero_economico} - ${item.producto__producto}</option>`;
              });

              llanta.innerHTML = options;
            })
            .catch((error) => console.error(error));

          break;

        case 'renovada':
          fetch('/api/tiresearchtaller?inventario=Renovada')
            .then((res) => res.json())
            .then((json) => {
              let options = '';

              json.result.forEach((item: any) => {
                options += `<option value="${item.numero_economico}">${item.numero_economico} - ${item.producto__producto}</option>`;
              });

              llanta.innerHTML = options;
            })
            .catch((error) => console.error(error));

          break;

        case 'servicio':
          fetch('/api/tiresearchtaller?inventario=Servicio')
            .then((res) => res.json())
            .then((json) => {
              let options = '';

              json.result.forEach((item: any) => {
                options += `<option value="${item.numero_economico}">${item.numero_economico} - ${item.producto__producto}</option>`;
              });

              llanta.innerHTML = options;
            })
            .catch((error) => console.error(error));

          break;
      }
    }

    if (target.name === 'nuevaLlanta') {
      const datalist = target.nextElementSibling as HTMLDataListElement;
      const list = Array(...datalist.querySelectorAll('option')).map(
        (item) => item.value
      );

      if (!list.includes(target.value)) {
        target.value = '';

        Swal.fire(
          'Error',
          'El valor no coincide con ningun número económico',
          'info'
        );
      }
    }
  });
})();

// * Rotación

(() => {
  /* Listening for a change event on the radio buttons. */
  document.addEventListener('change', (e) => {
    const target = e.target as HTMLInputElement;

    /* Filtering the array of objects and returning the objects that do not have the same id as the
    target.dataset.radioid. */
    if (target.value === 'mismo') {
      const tires = document.querySelector(
        `[data-rotar-id="${target.dataset.radioid}"] input[value="${target.dataset.radioid}"]`
      ) as HTMLInputElement;
      tires.disabled = true;
    }

    /* Fetching data from an API and populating a select element with the data. */
    if (target.value === 'otro') {
      const origen = document.getElementById(
        `origen-llanta-${target.dataset.radioid}`
      ) as HTMLInputElement;
      const vehiculoOrigen = document.getElementById(
        `origen-vehiculo-${target.dataset.radioid}`
      ) as HTMLInputElement;
      const kmMontado = document.getElementById(
        `origen-km_montadoo-${target.dataset.radioid}`
      ) as HTMLInputElement;

      // * Sacar los hidden inputs seleccionados
      const container = origen.parentElement?.parentElement;
      const destinoVehiculo = container?.querySelector(
        '[name="destino-vehiculo"]'
      ) as HTMLInputElement;
      const destinoLlanta = container?.querySelector(
        '[name="destino-llanta"]'
      ) as HTMLInputElement;

      // origen.addEventListener('change', (e) => {
      //   destinoLlanta.value = origen.value;
      // });

      origen.innerHTML = `<option value="">Seleccione una llanta</option>`;
      const inputOrigen =
        vehiculoOrigen.previousElementSibling as HTMLInputElement;
      let list: any[] = [];
      // const container = origen.parentElement?.parentElement;
      // const destinoVehiculo = container?.querySelector('[name="destino-vehiculo"]') as HTMLInputElement;

      fetch('/api/vehicleandtiresearchtaller')
        .then((res) => (res.ok ? res.json() : Promise.reject(res)))
        .then((json) => {
          json.vehiculos_list.forEach((item: any) => {
            vehiculoOrigen.innerHTML += `<option value="${item.numero_economico}"></option>`;
          });

          list = Array(...vehiculoOrigen.querySelectorAll('option')).map(
            (item) => item.value
          );
        })
        .catch((error) => console.error(error));

      // if (inputOrigen)

      /* Llanta */
      inputOrigen?.addEventListener('change', (e) => {
        // * Validar que sea un numero valido
        if (inputOrigen.value === '') return;

        if (!list.includes(inputOrigen.value)) {
          inputOrigen.value = '';
          Swal.fire('Error', 'El número economico no existe', 'error');
          return;
        }

        fetch('/api/vehicleandtiresearchtaller?id_select=' + inputOrigen.value)
          .then((res) => (res.ok ? res.json() : Promise.reject(res)))
          .then(({ km_max, km_min, llantas }: RotarResponse) => {
            kmMontado.max = km_max || '';
            kmMontado.min = km_min || '';
            origen.innerHTML = `<option value="">Seleccione un vehiculo</option>`;
            origen.innerHTML += llantas.map((item) => {
              return `<option value="${item.id}">${item.numero_economico} - ${item.posicion}</option>`;
            });
          })
          .catch((error) => console.error(error));
      });
    }
  });
})();

// * validar selección en modal

(() => {
  document.addEventListener('change', (e) => {
    const target = e.target as HTMLInputElement;

    if (target.matches('[data-view] input, [data-view] select')) {
      const id = target.dataset.idpadre;
      const { totalMontajes, totalServicios } = getSelectInputs(id!);

      if (totalServicios.length > 1) {
        document.querySelector<HTMLInputElement>(
          `[data-nav="${target.dataset.idpadre}"][value="desmontaje"]`
        )!.disabled = true;
      } else {
        document.querySelector<HTMLInputElement>(
          `[data-nav="${target.dataset.idpadre}"][value="desmontaje"]`
        )!.disabled = false;
      }

      if (totalMontajes.length > 0) {
        document.querySelector<HTMLInputElement>(
          `[data-nav="${target.dataset.idpadre}"][value="sr"]`
        )!.disabled = true;
      } else {
        document.querySelector<HTMLInputElement>(
          `[data-nav="${target.dataset.idpadre}"][value="sr"]`
        )!.disabled = false;
      }
    }
  });
})();

(() => {
  document.addEventListener('change', (e) => {
    const target = e.target as HTMLInputElement;

    if (target.name === 'llantaOrigen') {
      const id = target.dataset.idpadre;
      const options = Array(
        ...target.querySelectorAll<HTMLOptionElement>('option')
      );
      let selectedOption = options.find(
        (item) => item.value === target.value
      )?.textContent;

      const destinoLlanta = document.querySelector<HTMLInputElement>(
        `[name="destino_llanta"][data-idpadre="${id}"]`
      );

      console.log({ destinoLlanta });

      destinoLlanta!.value = selectedOption!;
    }
  });
})();
